SELECT * FROM REQUESTS R, IPM_CLEARING_RTRVL I
WHERE R.IPM_CLEARING_ID = I.CLEARING_ID
AND R.ACQ_RESPONSE_CD != 'N'
AND R.ACQ_NOTIF_DTTM IS NULL
AND R.ARC_DB_DTTM< TRUNC(SYSDATE)
AND ROWNUM <=2000
AND NVL(I.P0850_PRCSS_AGRMT_ID,'GLOBAL') = 'GLOBAL